server:
  port: 9527
  
spring:
  application:
    name: topcloud-zuul-gateway-9527
    
zuul: 
  #单个
  ignored-services: topcloud-dept
  #多个ignored-services: "*"
  #公共前缀
  prefix: /topxin
  routes: 
    mydept.serviceId: topcloud-dept
    mydept.path: /mydept/**
    
 
eureka:
  instance:
    instance-id: gateway-9572
    prefer-ip-address: true
  client:
    service-url:
      # 单机版配置defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
 
info:
  app.name: topcloud-zuul-gateway
  company.name: www.topcloud.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}