server: 
  port: 80  
  
feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    service-url:
      defaultZone: eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: false

                                                  